server:
  port: 8888
  servlet:
    context-path: /short-url

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/uhome?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root
      initial-size: 1
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 30000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis:
  mapper-locations: classpath:/com/mapper/*.xml

logging:
  level:
    root: info
    com.shorturl: debug
