server:
  port: 8888
  servlet:
    context-path: /short-url

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/uhome?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.shorturl: debug
